#!/bin/bash
if [ ! -f "data.json" ]; then
	echo "Error: data.json not found. Please run task 0x00 first."
	exit 1
fi
jq -r '"\(.name) \(.types[0].type.name) \(.weight) \(.height)"' data.json | \
awk '{
	name = toupper(substr($1,1,1)) substr($1,2);
	type = toupper(substr($2,1,1)) substr($2,2);
	weight = $3 / 10;
	height = $4 / 10;
	printf "%s is of type %s, weighs %gkg, and is %gm tall.\n", name, type, weight, height
}'
